#!/bin/bash
# Defining where the live code sits on the server
TARGET="/home/ubuntu/production_app/live"
GIT_DIR="/home/ubuntu/production_app/stargazer.git"

mkdir -p "$TARGET"

echo "--- CI/CD: Checking out new code ---"
# Extracts the files from the Git vault into the live folder
git --work-tree="$TARGET" --git-dir="$GIT_DIR" checkout -f main

# Entering the project directory
cd "$TARGET/Large Scale Machine Learning Final Project"

echo "--- CI/CD: Rebuilding Docker Container ---"
# Stop and remove the old version of the app
docker stop stargazer-prod || true
docker rm stargazer-prod || true

# Build and Run
docker build -t stargazer-final .
docker run -d -p 5100:5100 --name stargazer-prod stargazer-final

echo "--- CI/CD SUCCESS: The Star Predictor is updated and live! ---"
